### ISSUE TITLE
PEP 621 打包

### ISSUE THREAD

**Issue by mokurin000** [u-wlkjyy/gyscnSpirder#1]
## 好处

- 易于分发/更容易被作为依赖引入
- 可以装入 site-packages
- 可以使用绝对路径引用模块

**Comment by u-wlkjyy** [comment]
不好意思，最近没看到消息，一会儿我合并一下


------------------ 原始邮件 ------------------
发件人: 莯凛 ***@***.***&gt;
发送时间: 2024年8月6日 12:25
收件人: u-wlkjyy/gyscnSpirder ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [u-wlkjyy/gyscnSpirder] PEP 621 打包 (Issue #1)





 
好处
  
易于分发/更容易被作为依赖引入
 
可以装入 site-packages
 
可以使用绝对路径引用模块
